services:
  # El API de NestJS
  asescon-api:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        DIRECT_URL: ${DIRECT_URL}
    container_name: asescon-api
    restart: always
    ports:
      - '3001:3001'
    environment:
      # Neon usa URLs separadas para conexiones directas y pooled
      NODE_ENV: production
      PORT: 3001

      DATABASE_URL: ${DATABASE_URL}
      DIRECT_URL: ${DIRECT_URL}

      JWT_SECRET: ${JWT_SECRET:-secret}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}