// src/audit/constants/audit-actions.ts
export const AuditActions = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  TWO_FACTOR_SENT: '2FA_SENT',
  TWO_FACTOR_VERIFIED: '2FA_VERIFIED',
  CONTACT_FORM_RECEIVED: 'CONTACT_RECEIVED',
  DIAGNOSTIC_COMPLETED: 'DIAGNOSTIC_DONE',
  DATABASE_ERROR: 'DB_ERROR',
} as const;
